from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional

class AskRequest(BaseModel):
    question: str = Field(description="The natural language question to ask the RAG pipeline.")
    top_k: int = Field(default=5, description="The maximum number of matching document chunks to retrieve.")
    where_filter: Optional[Dict[str, Any]] = Field(default=None, description="Optional metadata filter dictionary for scoped collection searches.")

class AskResponse(BaseModel):
    answer: str = Field(description="The generated answer from the language model backend.")
    sources: List[str] = Field(description="List of matching source segment identifiers utilized for context generation.")
    model_name: str = Field(description="The identifier string of the text generation model used.")
    prompt_tokens: int = Field(description="Number of tokens processed within the built prompt layout.")
    completion_tokens: int = Field(description="Number of tokens generated by the inference completion layer.")
    total_tokens: int = Field(description="Sum total of raw interaction lifecycle processing tokens consumed.")
    latency: float = Field(description="The overall time taken to process the query execution pipeline, tracked in seconds.")
    created_at: str = Field(description="ISO-8601 formatted string capturing the generation completion timestamp.")

class UploadRequest(BaseModel):
    document_id: str = Field(description="A unique primary identifier used to trace the document across index files.")
    file_name: str = Field(description="The source filename string.")
    raw_text: str = Field(description="The raw string content extracted from the document source payload.")
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="Additional custom metadata dictionaries attached to the text sequence structures.")

class UploadResponse(BaseModel):
    success: bool = Field(description="Flag signaling if the ingestion pipeline execution completed without crashing.")
    message: str = Field(description="Descriptive status log detail explaining the outcome of the request.")
    document_id: str = Field(description="The unique system identifier mapped to the document state index entry.")

class HealthResponse(BaseModel):
    status: str = Field(description="Current structural operational status of the service node API instance.")
    llm_provider: str = Field(description="The identifier label tracking the current configured active text inference engine.")
    embedding_model: str = Field(description="The model signature currently handling tokenization vectors.")
    vector_database: str = Field(description="The active database technology layer managing document indexes.")
    timestamp: str = Field(description="System generation validation clock reading captured in ISO-8601 notation.")
